version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: server
    command: uvicorn src.api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - .env
