version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: system/Dockerfile
    container_name: backend
    entrypoint: ./entrypoint.sh
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - ./shared-files/database/dump:/app/dump
      - ./shared-files/database/postgresql:/var/lib/postgresql/data
