"""a

Revision ID: 63ca63ba35b6
Revises: 8777e0a9fc3f
Create Date: 2022-02-09 16:35:17.759582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ca63ba35b6'
down_revision = '8777e0a9fc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
