"""Initial commit

Revision ID: 8777e0a9fc3f
Revises: 
Create Date: 2022-02-09 12:19:47.737160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8777e0a9fc3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_id'), 'condition', ['id'], unique=False)
    op.create_table('day_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_time_id'), 'day_time', ['id'], unique=False)
    op.create_table('wind_direction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('direction', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wind_direction_id'), 'wind_direction', ['id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('t_min', sa.Integer(), nullable=True),
    sa.Column('t_max', sa.Integer(), nullable=True),
    sa.Column('pressure_min', sa.Integer(), nullable=True),
    sa.Column('pressure_max', sa.Integer(), nullable=True),
    sa.Column('humidity_min', sa.Integer(), nullable=True),
    sa.Column('humidity_max', sa.Integer(), nullable=True),
    sa.Column('wind_speed_min', sa.Integer(), nullable=True),
    sa.Column('wind_speed_max', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('wind_direction_id', sa.Integer(), nullable=True),
    sa.Column('day_time_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_time_id'], ['day_time.id'], ),
    sa.ForeignKeyConstraint(['wind_direction_id'], ['wind_direction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_id'), 'weather', ['id'], unique=False)
    op.create_table('weather_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
    sa.PrimaryKeyConstraint('id', 'weather_id', 'condition_id')
    )
    op.create_index(op.f('ix_weather_condition_id'), 'weather_condition', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_condition_id'), table_name='weather_condition')
    op.drop_table('weather_condition')
    op.drop_index(op.f('ix_weather_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_wind_direction_id'), table_name='wind_direction')
    op.drop_table('wind_direction')
    op.drop_index(op.f('ix_day_time_id'), table_name='day_time')
    op.drop_table('day_time')
    op.drop_index(op.f('ix_condition_id'), table_name='condition')
    op.drop_table('condition')
    # ### end Alembic commands ###
